// lib/widget/dropdown.dart

import 'package:armiyaapp/model/autogenerated.dart';
import 'package:flutter/material.dart';

class CustomDropdown extends StatelessWidget {
  final String hintText;
  final List<Facility> items;
  final String? selectedItem;
  final ValueChanged<String?> onChanged;
  final String? Function(String?)? validator;

  const CustomDropdown({
    super.key,
    required this.hintText,
    required this.items,
    required this.selectedItem,
    required this.onChanged,
    this.validator,
  });

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      decoration: const InputDecoration(
        border: OutlineInputBorder(),
        contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      ),
      hint: Text(hintText),
      value: selectedItem,
      isExpanded: true,
      items: items.map((Facility facility) {
        return DropdownMenuItem<String>(
          value: facility.tesisAd,
          child: Text(facility.tesisAd!),
        );
      }).toList(),
      onChanged: onChanged,
      validator: validator,
    );
  }
}
